2024-08-09 00:00:43,923 INFO    MainThread:29068 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2024-08-09 00:00:43,924 INFO    MainThread:29068 [wandb_setup.py:_flush():76] Configure stats pid to 29068
2024-08-09 00:00:43,925 INFO    MainThread:29068 [wandb_setup.py:_flush():76] Loading settings from /home/tuyen/.config/wandb/settings
2024-08-09 00:00:43,926 INFO    MainThread:29068 [wandb_setup.py:_flush():76] Loading settings from /mnt/c/Code/YoloV8/wandb/settings
2024-08-09 00:00:43,926 INFO    MainThread:29068 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-08-09 00:00:43,926 INFO    MainThread:29068 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-08-09 00:00:43,927 INFO    MainThread:29068 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-08-09 00:00:43,927 INFO    MainThread:29068 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-08-09 00:00:43,928 INFO    MainThread:29068 [wandb_init.py:_log_setup():520] Logging user logs to /mnt/c/Code/YoloV8/wandb/run-20240809_000043-048200d8/logs/debug.log
2024-08-09 00:00:43,928 INFO    MainThread:29068 [wandb_init.py:_log_setup():521] Logging internal logs to /mnt/c/Code/YoloV8/wandb/run-20240809_000043-048200d8/logs/debug-internal.log
2024-08-09 00:00:43,929 INFO    MainThread:29068 [wandb_init.py:init():560] calling init triggers
2024-08-09 00:00:43,929 INFO    MainThread:29068 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'task': 'detect', 'mode': 'train', 'model': 'yolov8n.pt', 'data': '/mnt/c/Code/YoloV8/data/mydataset.yaml', 'epochs': 1, 'time': None, 'patience': 100, 'batch': 16, 'imgsz': 640, 'save': True, 'save_period': -1, 'cache': False, 'device': None, 'workers': 8, 'project': None, 'name': 'train3', 'exist_ok': False, 'pretrained': True, 'optimizer': 'auto', 'verbose': True, 'seed': 0, 'deterministic': True, 'single_cls': False, 'rect': False, 'cos_lr': False, 'close_mosaic': 10, 'resume': False, 'amp': True, 'fraction': 1.0, 'profile': False, 'freeze': None, 'multi_scale': False, 'overlap_mask': True, 'mask_ratio': 4, 'dropout': 0.0, 'val': True, 'split': 'val', 'save_json': False, 'save_hybrid': False, 'conf': None, 'iou': 0.7, 'max_det': 300, 'half': False, 'dnn': False, 'plots': True, 'source': None, 'vid_stride': 1, 'stream_buffer': False, 'visualize': False, 'augment': False, 'agnostic_nms': False, 'classes': None, 'retina_masks': False, 'embed': None, 'show': False, 'save_frames': False, 'save_txt': False, 'save_conf': False, 'save_crop': False, 'show_labels': True, 'show_conf': True, 'show_boxes': True, 'line_width': None, 'format': 'torchscript', 'keras': False, 'optimize': False, 'int8': False, 'dynamic': False, 'simplify': False, 'opset': None, 'workspace': 4, 'nms': False, 'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 7.5, 'cls': 0.5, 'dfl': 1.5, 'pose': 12.0, 'kobj': 1.0, 'label_smoothing': 0.0, 'nbs': 64, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'bgr': 0.0, 'mosaic': 1.0, 'mixup': 0.0, 'copy_paste': 0.0, 'auto_augment': 'randaugment', 'erasing': 0.4, 'crop_fraction': 1.0, 'cfg': None, 'tracker': 'botsort.yaml', 'save_dir': 'runs/detect/train3'}
2024-08-09 00:00:43,930 INFO    MainThread:29068 [wandb_init.py:init():610] starting backend
2024-08-09 00:00:43,930 INFO    MainThread:29068 [wandb_init.py:init():614] setting up manager
2024-08-09 00:00:43,934 ERROR   MainThread:29068 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/home/tuyen/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
  File "/home/tuyen/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 615, in init
    manager._inform_init(
  File "/home/tuyen/.local/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/tuyen/.local/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home/tuyen/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/tuyen/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/tuyen/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/tuyen/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
